services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        environment:

            - MONGODB_URI=mongodb://mongo:27017/mong # Alterar para o banco de dados
            - MERCADO_PAGO_API=https://api.mercadopago.com
            - MERCADO_PAGO_CLIENT_SECRET='IyaI124z9fuUZUPAjslnGvdo0S4IVF3t'
            - MERCADO_PAGO_CLIENT_ID='1824214370596611'
            - MERCADO_PAGO_QR_CODE_API=https://api.mercadopago.com/instore/orders/qr/seller/collectors
            - MERCADO_PAGO_WEBHOOK=https://c318-2804-7f4-5218-d989-19f0-8213-bd-69d8.ngrok-free.app
        depends_on:
            - mongo
        volumes:
            - ./src:/app/src

    mongo:
        image: mongo:latest
        command:
            - '--logpath'
            - '/var/log/mongodb/mongod.log'
        volumes:
            - mongo_data:/data/db # Persistir os dados do MongoDB

volumes:
    mongo_data:
